export const WEB_API = {
  clientDownloads: '/api/client-downloads',
  authLogin: '/api/auth/login',
  authRegister: '/api/auth/register',
  authRenew: '/api/auth/renew',
  consoleLogin: '/api/auth/console-login',
  prepareDeviceLogin: '/api/auth/device-login-devices',
  completeDeviceLogin: (deviceId: string) => `/api/auth/device-login-devices/${encodeURIComponent(deviceId)}/complete`,
  userPassword: (userId: string) => `/api/users/${encodeURIComponent(userId)}/password`,
  userEntitlement: (userId: string) => `/api/users/${encodeURIComponent(userId)}/entitlement`,
  userAliases: '/api/user-aliases',
  devicesVisible: (userId = '') => `/api/devices/visible${userId ? `?userId=${encodeURIComponent(userId)}` : ''}`,
  devicesRegister: '/api/devices/register',
  device: (deviceId: string, actorUserId = '') => `/api/devices/${encodeURIComponent(deviceId)}${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  deviceInvites: (userId = '') => `/api/device-invites${userId ? `?userId=${encodeURIComponent(userId)}` : ''}`,
  deviceInviteAccept: '/api/device-invites/accept',
  deviceBootstrapKeys: (userId = '') => `/api/web/device-bootstrap-keys${userId ? `?userId=${encodeURIComponent(userId)}` : ''}`,
  deviceBootstrapKeyRevoke: (keyId: string) => `/api/web/device-bootstrap-keys/${encodeURIComponent(keyId)}/revoke`,
  networks: (userId = '') => `/api/networks${userId ? `?userId=${encodeURIComponent(userId)}` : ''}`,
  network: (networkId: string) => `/api/networks/${encodeURIComponent(networkId)}`,
  networkDevices: (networkId: string) => `/api/networks/${encodeURIComponent(networkId)}/devices`,
  networkDevice: (networkId: string, deviceId: string) => `/api/networks/${encodeURIComponent(networkId)}/devices/${encodeURIComponent(deviceId)}`,
  dnsZones: (networkId: string) => `/api/networks/${encodeURIComponent(networkId)}/dns/zones`,
  dnsZone: (networkId: string, zoneId: string) => `/api/networks/${encodeURIComponent(networkId)}/dns/zones/${encodeURIComponent(zoneId)}`,
  dnsRecords: (networkId: string) => `/api/networks/${encodeURIComponent(networkId)}/dns/records`,
  dnsRecord: (networkId: string, recordId: string) => `/api/networks/${encodeURIComponent(networkId)}/dns/records/${encodeURIComponent(recordId)}`,
  publicMappings: (networkId: string) => `/api/networks/${encodeURIComponent(networkId)}/public-mappings`,
  publicMapping: (networkId: string, mappingId: string) => `/api/networks/${encodeURIComponent(networkId)}/public-mappings/${encodeURIComponent(mappingId)}`,
  securityGroups: (networkId: string) => `/api/networks/${encodeURIComponent(networkId)}/security-groups`,
  securityGroup: (networkId: string, securityGroupId: string) => `/api/networks/${encodeURIComponent(networkId)}/security-groups/${encodeURIComponent(securityGroupId)}`,
  securityRules: (securityGroupId: string) => `/api/security-groups/${encodeURIComponent(securityGroupId)}/rules`,
  securityRule: (ruleId: string) => `/api/security-groups/rules/${encodeURIComponent(ruleId)}`,
} as const;
