[package]
name = "client-core-ffi"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
client-core = { path = "../client-core" }
client-core-platform = { path = "../client-core-platform" }
client-core-service = { path = "../client-core-service" }
serde_json.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
libc = "0.2"
