[workspace]
members = [
    "crates/app-core",
    "crates/app-core-cli",
    "crates/app-core-helper",
    "crates/app-core-service",
    "crates/control-mqtt-client",
    "crates/controller-client",
    "crates/nat",
    "crates/p2p",
    "crates/relay-client",
    "crates/tunnel",
    "crates/ffi-bridge",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"
