#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)

SERVER_HOST="${1:-${SERVER_HOST:-}}"
DOMAIN="${2:-${DOMAIN:-dev.staticlss.com}}"
REMOTE_DIR="${3:-${REMOTE_DIR:-/opt/slan}}"
OUT_DIR="${OUT_DIR:-$ROOT_DIR/.tmp/remote-deploy}"

if [ -z "$SERVER_HOST" ]; then
  cat >&2 <<'EOF'
Usage:
  scripts/generate_remote_deploy_script.sh <server-ip-or-domain> [domain] [remote-dir]

Examples:
  scripts/generate_remote_deploy_script.sh 1.2.3.4 dev.staticlss.com
  scripts/generate_remote_deploy_script.sh slan-dev.example.com dev.staticlss.com /opt/slan

Output:
  .tmp/remote-deploy/.env.prod
  .tmp/remote-deploy/deploy_to_<server>.sh
EOF
  exit 2
fi

SAFE_HOST=$(printf '%s' "$SERVER_HOST" | tr -c 'A-Za-z0-9._-' '_')
DEPLOY_SCRIPT="$OUT_DIR/deploy_to_${SAFE_HOST}.sh"
ENV_FILE="$OUT_DIR/.env.prod"

mkdir -p "$OUT_DIR"

rand_hex() {
  openssl rand -hex "$1"
}

cat >"$ENV_FILE" <<EOF
# Generated by scripts/generate_remote_deploy_script.sh
# Server: ${SERVER_HOST}
# Domain: ${DOMAIN}

POSTGRES_PASSWORD=$(rand_hex 24)
POSTGRES_BIND_HOST=127.0.0.1
POSTGRES_PUBLIC_PORT=15432

REDIS_BIND_HOST=127.0.0.1
REDIS_PUBLIC_PORT=16379

BIFROMQ_MQTT_PORT=1883
BIFROMQ_AUTH_PROVIDER_URL=http://server-biz:8080/mqtt/bifromq
BIFROMQ_MEM_LIMIT=2g
BIFROMQ_MEM_LIMIT_BYTES=2147483648

SLAN_BIZ_PUBLIC_PORT=28080
SLAN_WEB_PORT=24200
SLAN_MAIN_PORT=24201

SLAN_WEB_CONSOLE_URL=http://web.${DOMAIN}
SLAN_GLOBAL_DEVICE_DOMAIN=staticlss.com
SLAN_RELAY_ENDPOINTS=${SERVER_HOST}:29110
SLAN_RELAY_REGION_ID=dev
SLAN_RELAY_TICKET_SECRET=$(rand_hex 32)
SLAN_INTERNAL_WIRE_TOKEN=$(rand_hex 32)
SLAN_WIRE_TICKET_SECRET=$(rand_hex 32)
SLAN_WIRE_TICKET_SECRETS=$(rand_hex 32)
SLAN_WIRE_NODE_HEARTBEAT_FRESHNESS_SECONDS=120

SLAN_MQTT_ENABLED=true
SLAN_MQTT_BROKER_URL=mqtt://bifromq:1883
SLAN_MQTT_PUBLIC_BROKER_URL=mqtt://${SERVER_HOST}:1883
SLAN_MQTT_PASSWORD_SECRET=$(rand_hex 32)
SLAN_MQTT_PUBLISH_TIMEOUT_MILLISECONDS=15000

SLAN_WIRE_PORT=29100
SLAN_WIRE_B_PORT=29101

SLAN_WIRE_RELAY_PORT=29110
SLAN_WIRE_RELAY_ADMIN_PORT=29111
SLAN_WIRE_RELAY_REGION_ID=dev
SLAN_WIRE_RELAY_NODE_ID=relay-dev-1
SLAN_WIRE_RELAY_PUBLIC_HOST=${SERVER_HOST}

SLAN_WIRE_RELAY_B_PORT=29112
SLAN_WIRE_RELAY_B_ADMIN_PORT=29113
SLAN_WIRE_RELAY_B_REGION_ID=dev
SLAN_WIRE_RELAY_B_NODE_ID=relay-dev-2
SLAN_WIRE_RELAY_B_PUBLIC_HOST=${SERVER_HOST}
SLAN_WIRE_RELAY_B_PUBLIC_UDP_PORT=29112

SLAN_WIRE_DERP_PORT=29120
SLAN_WIRE_DERP_ADMIN_PORT=29121
SLAN_WIRE_DERP_REGION_ID=dev
SLAN_WIRE_DERP_NODE_ID=derp-dev-1
SLAN_WIRE_DERP_PUBLIC_HOST=${SERVER_HOST}
SLAN_WIRE_DERP_PUBLIC_PORT=29120

SLAN_WIRE_DERP_B_PORT=29122
SLAN_WIRE_DERP_B_ADMIN_PORT=29123
SLAN_WIRE_DERP_B_REGION_ID=dev
SLAN_WIRE_DERP_B_NODE_ID=derp-dev-2
SLAN_WIRE_DERP_B_PUBLIC_HOST=${SERVER_HOST}
SLAN_WIRE_DERP_B_PUBLIC_PORT=29122
EOF

cat >"$DEPLOY_SCRIPT" <<EOF
#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=\$(CDPATH= cd -- "\$(dirname "\$0")/../.." && pwd)

REMOTE_HOST="${SERVER_HOST}"
REMOTE_DIR="${REMOTE_DIR}"
ENV_SOURCE="\$(CDPATH= cd -- "\$(dirname "\$0")" && pwd)/.env.prod"
SSH_ENV="\$(CDPATH= cd -- "\$(dirname "\$0")" && pwd)/ssh.env"

if [ -f "\$SSH_ENV" ]; then
  set -a
  . "\$SSH_ENV"
  set +a
fi

REMOTE_USER="\${REMOTE_USER:-root}"
export REMOTE_USER

if [ ! -f "\$ENV_SOURCE" ]; then
  echo "env file not found: \$ENV_SOURCE" >&2
  exit 1
fi

cp "\$ENV_SOURCE" "\$ROOT_DIR/.env.prod"
"\$ROOT_DIR/scripts/remote_docker_deploy.sh" "\$REMOTE_HOST" "\$REMOTE_DIR" ".env.prod"
EOF

chmod +x "$DEPLOY_SCRIPT"

cat <<EOF
Generated:
  $ENV_FILE
  $DEPLOY_SCRIPT

Next:
  1. Check DNS points to ${SERVER_HOST}:
     api.${DOMAIN}
     web.${DOMAIN}
     ops.${DOMAIN}
     mqtt.${DOMAIN}
     wire.${DOMAIN}
     relay.${DOMAIN}
     derp.${DOMAIN}

  2. Run:
     $DEPLOY_SCRIPT

Optional password mode:
  If you use SSH password and have sshpass installed, create this local ignored file:
     $OUT_DIR/ssh.env

  Example:
     REMOTE_USER=root
     SSHPASS='your-root-password'

  Otherwise SSH will prompt for the root password normally.
EOF
