name: slan_app_core_plugin_platform_interface
description: Shared platform interface for the federated SLAN app_core Flutter plugin.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
