[workspace]
members = [
    "crates/client-core",
    "crates/client-core-ffi",
    "crates/client-core-helper",
    "crates/client-core-platform",
    "crates/client-core-service",
    "crates/control-mqtt-client",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
