#!/usr/bin/env sh

SLAN_DEFAULT_CONTROL_BASE_URL="${SLAN_DEFAULT_CONTROL_BASE_URL:-http://47.245.40.231:28080}"
# Legacy variable retained for scripts; management and runtime APIs now share one endpoint.
SLAN_DEFAULT_WEB_BASE_URL="${SLAN_DEFAULT_WEB_BASE_URL:-$SLAN_DEFAULT_CONTROL_BASE_URL}"
SLAN_DEFAULT_OPS_BASE_URL="${SLAN_DEFAULT_OPS_BASE_URL:-http://47.245.40.231:24201}"
SLAN_DEFAULT_MQTT_HOST="${SLAN_DEFAULT_MQTT_HOST:-47.245.40.231}"
