export const WEB_API = {
  clientDownloads: '/api/web/client-downloads',
  authLogin: '/api/web/auth/login',
  authRegister: '/api/web/auth/register',
  authRenew: '/api/web/auth/renew',
  userSessions: (userId: string) => `/api/web/users/${encodeURIComponent(userId)}/sessions`,
  userSessionRevoke: (userId: string, sessionId: string, actorUserId = '') => `/api/web/users/${encodeURIComponent(userId)}/sessions/${encodeURIComponent(sessionId)}/revoke${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  consoleLogin: '/api/web/auth/console-login',
  prepareDeviceLogin: '/api/web/auth/device-login-devices',
  completeDeviceLogin: (deviceId: string) => `/api/web/auth/device-login-devices/${encodeURIComponent(deviceId)}/complete`,
  userPassword: (userId: string) => `/api/web/users/${encodeURIComponent(userId)}/password`,
  userEntitlement: (userId: string) => `/api/web/users/${encodeURIComponent(userId)}/entitlement`,
  userAliases: '/api/web/user-aliases',
  userAliasesForUser: (userId = '') => userId ? `/api/web/users/${encodeURIComponent(userId)}/user-aliases` : '/api/web/user-aliases',
  devicesVisible: (userId = '') => userId ? `/api/web/users/${encodeURIComponent(userId)}/devices/visible` : '/api/web/devices/visible',
  deviceGroups: (userId: string) => `/api/web/users/${encodeURIComponent(userId)}/device-groups`,
  deviceGroup: (userId: string, groupId: string, actorUserId = '') => `/api/web/users/${encodeURIComponent(userId)}/device-groups/${encodeURIComponent(groupId)}${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  deviceGroupsForDevice: (userId: string, deviceId: string, actorUserId = '') => `/api/web/users/${encodeURIComponent(userId)}/devices/${encodeURIComponent(deviceId)}/groups${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  devicesRegister: '/api/web/devices/register',
  device: (deviceId: string, actorUserId = '') => `/api/web/devices/${encodeURIComponent(deviceId)}${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  deviceSessions: (deviceId: string) => `/api/web/devices/${encodeURIComponent(deviceId)}/sessions`,
  deviceSessionRevoke: (deviceId: string, sessionId: string, actorUserId = '') => `/api/web/devices/${encodeURIComponent(deviceId)}/sessions/${encodeURIComponent(sessionId)}/revoke${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  deviceInvites: (userId = '') => userId ? `/api/web/users/${encodeURIComponent(userId)}/device-invites` : '/api/web/device-invites',
  deviceInviteAccept: '/api/web/device-invites/accept',
  deviceBootstrapKeys: (userId = '') => userId ? `/api/web/users/${encodeURIComponent(userId)}/device-bootstrap-keys` : '/api/web/device-bootstrap-keys',
  deviceBootstrapKeyRevoke: (keyId: string, actorUserId = '') => `/api/web/device-bootstrap-keys/${encodeURIComponent(keyId)}/revoke${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  networks: (userId = '') => userId ? `/api/web/users/${encodeURIComponent(userId)}/networks` : '/api/web/networks',
  network: (networkId: string, actorUserId = '') => `/api/web/networks/${encodeURIComponent(networkId)}${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  networkDevices: (networkId: string) => `/api/web/networks/${encodeURIComponent(networkId)}/devices`,
  networkDevice: (networkId: string, deviceId: string, actorUserId = '') => `/api/web/networks/${encodeURIComponent(networkId)}/devices/${encodeURIComponent(deviceId)}${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  dnsZones: (networkId: string) => `/api/web/networks/${encodeURIComponent(networkId)}/dns/zones`,
  dnsZone: (networkId: string, zoneId: string, actorUserId = '') => `/api/web/networks/${encodeURIComponent(networkId)}/dns/zones/${encodeURIComponent(zoneId)}${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  dnsRecords: (networkId: string) => `/api/web/networks/${encodeURIComponent(networkId)}/dns/records`,
  dnsRecord: (networkId: string, recordId: string, actorUserId = '') => `/api/web/networks/${encodeURIComponent(networkId)}/dns/records/${encodeURIComponent(recordId)}${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  publicMappings: (networkId: string) => `/api/web/networks/${encodeURIComponent(networkId)}/public-mappings`,
  publicMapping: (networkId: string, mappingId: string, actorUserId = '') => `/api/web/networks/${encodeURIComponent(networkId)}/public-mappings/${encodeURIComponent(mappingId)}${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  securityGroups: (networkId: string) => `/api/web/networks/${encodeURIComponent(networkId)}/security-groups`,
  securityGroup: (networkId: string, securityGroupId: string, actorUserId = '') => `/api/web/networks/${encodeURIComponent(networkId)}/security-groups/${encodeURIComponent(securityGroupId)}${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
  securityRules: (securityGroupId: string) => `/api/web/security-groups/${encodeURIComponent(securityGroupId)}/rules`,
  securityRule: (ruleId: string, actorUserId = '') => `/api/web/security-groups/rules/${encodeURIComponent(ruleId)}${actorUserId ? `?actorUserId=${encodeURIComponent(actorUserId)}` : ''}`,
} as const;
