import Foundation

// Shared short aliases for the deepest adapter-backed runtime chain.
// They keep the existing concrete types intact while making the shared
// implementation and tests readable enough to maintain.

typealias WireGuardKitDeepBackedRootHandleConfiguration =
  WireGuardKitAdapterBackedSessionHandleConfiguration
typealias WireGuardKitDeepBackedRootHandleConfigurationMapper =
  WireGuardKitAdapterBackedSessionHandleConfigurationMapper
typealias WireGuardKitDeepBackedRootHandleTerminalConfigurationMapper =
  WireGuardKitAdapterBackedSessionHandleTerminalConfigurationMapper
typealias WireGuardKitDeepBackedRootHandleControlling =
  WireGuardKitAdapterBackedSessionHandleControlling
typealias WireGuardKitDeepBackedRootHandleCreating =
  WireGuardKitAdapterBackedSessionHandleCreating
typealias WireGuardKitDeepBackedRootHandleFactorying =
  WireGuardKitAdapterBackedSessionHandleFactorying
typealias WireGuardKitDeepBackedRootHandle =
  WireGuardKitAdapterBackedSessionHandle
typealias UnavailableWireGuardKitDeepBackedRootHandleCreator =
  UnavailableWireGuardKitAdapterBackedSessionHandleCreator
typealias WireGuardKitDeepBackedRootHandleCreator =
  WireGuardKitAdapterBackedSessionHandleCreator
typealias UnavailableWireGuardKitDeepBackedRootHandleFactory =
  UnavailableWireGuardKitAdapterBackedSessionHandleFactory
typealias WireGuardKitDeepBackedRootHandleFactory =
  WireGuardKitAdapterBackedSessionHandleFactory

typealias WireGuardKitDeepBackedNativeHandleConfiguration =
  WireGuardKitAdapterBackedSessionNativeHandleConfiguration
typealias WireGuardKitDeepBackedNativeHandleConfigurationMapper =
  WireGuardKitAdapterBackedSessionNativeHandleConfigurationMapper
typealias WireGuardKitDeepBackedNativeHandleTerminalConfigurationMapper =
  WireGuardKitAdapterBackedSessionNativeHandleTerminalConfigurationMapper
typealias WireGuardKitDeepBackedNativeHandleControlling =
  WireGuardKitAdapterBackedSessionNativeHandleControlling
typealias WireGuardKitDeepBackedNativeHandleCreating =
  WireGuardKitAdapterBackedSessionNativeHandleCreating
typealias WireGuardKitDeepBackedNativeHandleFactorying =
  WireGuardKitAdapterBackedSessionNativeHandleFactorying
typealias WireGuardKitDeepBackedNativeHandle =
  WireGuardKitAdapterBackedSessionNativeHandle
typealias UnavailableWireGuardKitDeepBackedNativeHandle =
  UnavailableWireGuardKitAdapterBackedSessionNativeHandle
typealias UnavailableWireGuardKitDeepBackedNativeHandleCreator =
  UnavailableWireGuardKitAdapterBackedSessionNativeHandleCreator
typealias WireGuardKitDeepBackedNativeHandleCreator =
  WireGuardKitAdapterBackedSessionNativeHandleCreator
typealias UnavailableWireGuardKitDeepBackedNativeHandleFactory =
  UnavailableWireGuardKitAdapterBackedSessionNativeHandleFactory
typealias WireGuardKitDeepBackedNativeHandleFactory =
  WireGuardKitAdapterBackedSessionNativeHandleFactory

typealias WireGuardKitDeepAdapterHandleConfiguration =
  WireGuardKitAdapterBackedSessionAdapterHandleConfiguration
typealias WireGuardKitDeepAdapterHandleConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleConfigurationMapper
typealias WireGuardKitDeepAdapterHandleTerminalConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleTerminalConfigurationMapper
typealias WireGuardKitDeepAdapterHandleControlling =
  WireGuardKitAdapterBackedSessionAdapterHandleControlling
typealias WireGuardKitDeepAdapterHandleCreating =
  WireGuardKitAdapterBackedSessionAdapterHandleCreating
typealias WireGuardKitDeepAdapterHandle =
  WireGuardKitAdapterBackedSessionAdapterHandle
typealias UnavailableWireGuardKitDeepAdapterHandleCreator =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleCreator
typealias WireGuardKitDeepAdapterHandleCreator =
  WireGuardKitAdapterBackedSessionAdapterHandleCreator

typealias WireGuardKitDeepAdapterSessionConfiguration =
  WireGuardKitAdapterBackedSessionAdapterHandleSessionConfiguration
typealias WireGuardKitDeepAdapterSessionConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleSessionConfigurationMapper
typealias WireGuardKitDeepAdapterSessioning =
  WireGuardKitAdapterBackedSessionAdapterHandleSessioning
typealias WireGuardKitDeepAdapterSessionCreating =
  WireGuardKitAdapterBackedSessionAdapterHandleSessionCreating
typealias WireGuardKitDeepAdapterSessionFactorying =
  WireGuardKitAdapterBackedSessionAdapterHandleSessionFactorying
typealias WireGuardKitDeepAdapterSession =
  WireGuardKitAdapterBackedSessionAdapterHandleSession
typealias UnavailableWireGuardKitDeepAdapterSession =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleSession
typealias UnavailableWireGuardKitDeepAdapterSessionCreator =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleSessionCreator
typealias WireGuardKitDeepAdapterSessionCreator =
  WireGuardKitAdapterBackedSessionAdapterHandleSessionCreator
typealias UnavailableWireGuardKitDeepAdapterSessionFactory =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleSessionFactory
typealias WireGuardKitDeepAdapterSessionFactory =
  WireGuardKitAdapterBackedSessionAdapterHandleSessionFactory

typealias WireGuardKitDeepNativeSessionConfiguration =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionConfiguration
typealias WireGuardKitDeepNativeSessionConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionConfigurationMapper
typealias WireGuardKitDeepNativeSessioning =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessioning
typealias WireGuardKitDeepNativeSessionCreating =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionCreating
typealias WireGuardKitDeepNativeSessionFactorying =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionFactorying
typealias WireGuardKitDeepNativeSession =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSession
typealias UnavailableWireGuardKitDeepNativeSessionCreator =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionCreator
typealias WireGuardKitDeepNativeSessionCreator =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionCreator
typealias UnavailableWireGuardKitDeepNativeSessionFactory =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionFactory
typealias WireGuardKitDeepNativeSessionFactory =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionFactory

typealias WireGuardKitDeepRuntimeBridgeHandleConfiguration =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleConfiguration
typealias WireGuardKitDeepRuntimeBridgeHandleConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleConfigurationMapper
typealias WireGuardKitDeepRuntimeBridgeHandleControlling =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleControlling
typealias WireGuardKitDeepRuntimeBridgeHandleCreating =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleCreating
typealias WireGuardKitDeepRuntimeBridgeHandle =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandle
typealias UnavailableWireGuardKitDeepRuntimeBridgeHandleCreator =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleCreator
typealias WireGuardKitDeepRuntimeBridgeHandleCreator =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleCreator

typealias WireGuardKitDeepRuntimeHandleConfiguration =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleConfiguration
typealias WireGuardKitDeepRuntimeHandleConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleConfigurationMapper
typealias WireGuardKitDeepRuntimeHandleTerminalConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleTerminalConfigurationMapper
typealias WireGuardKitDeepRuntimeHandleControlling =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleControlling
typealias WireGuardKitDeepRuntimeHandleCreating =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleCreating
typealias WireGuardKitDeepRuntimeHandle =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandle
typealias UnavailableWireGuardKitDeepRuntimeHandleCreator =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleCreator
typealias WireGuardKitDeepRuntimeHandleCreator =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleCreator

typealias WireGuardKitDeepRuntimeSessionConfiguration =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionConfiguration
typealias WireGuardKitDeepRuntimeSessionConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionConfigurationMapper
typealias WireGuardKitDeepRuntimeSessionTerminalConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionTerminalConfigurationMapper
typealias WireGuardKitDeepRuntimeSessioning =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessioning
typealias WireGuardKitDeepRuntimeSessionCreating =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionCreating
typealias WireGuardKitDeepRuntimeSessionFactorying =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionFactorying
typealias WireGuardKitDeepRuntimeSession =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSession
typealias UnavailableWireGuardKitDeepRuntimeSessionCreator =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionCreator
typealias WireGuardKitDeepRuntimeSessionCreator =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionCreator
typealias UnavailableWireGuardKitDeepRuntimeSessionFactory =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionFactory
typealias WireGuardKitDeepRuntimeSessionFactory =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionFactory

typealias WireGuardKitDeepBackedSessionConfiguration =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionConfiguration
typealias WireGuardKitDeepBackedSessionConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionConfigurationMapper
typealias WireGuardKitDeepBackedSessioning =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessioning
typealias WireGuardKitDeepBackedSessionCreating =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionCreating
typealias WireGuardKitDeepBackedSessionFactorying =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionFactorying
typealias WireGuardKitDeepBackedSession =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSession
typealias UnavailableWireGuardKitDeepBackedSessionCreator =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionCreator
typealias WireGuardKitDeepBackedSessionCreator =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionCreator
typealias UnavailableWireGuardKitDeepBackedSessionFactory =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionFactory
typealias WireGuardKitDeepBackedSessionFactory =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionFactory

typealias WireGuardKitDeepBackedHandleConfiguration =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleConfiguration
typealias WireGuardKitDeepBackedHandleConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleConfigurationMapper
typealias WireGuardKitDeepBackedHandleControlling =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleControlling
typealias WireGuardKitDeepBackedHandleCreating =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleCreating
typealias WireGuardKitDeepBackedHandleFactorying =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleFactorying
typealias WireGuardKitDeepBackedHandle =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandle
typealias UnavailableWireGuardKitDeepBackedHandleCreator =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleCreator
typealias WireGuardKitDeepBackedHandleCreator =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleCreator
typealias UnavailableWireGuardKitDeepBackedHandleFactory =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleFactory
typealias WireGuardKitDeepBackedHandleFactory =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleFactory

typealias WireGuardKitDeepBackedHandleSessionConfiguration =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionConfiguration
typealias WireGuardKitDeepBackedHandleSessionConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionConfigurationMapper
typealias WireGuardKitDeepBackedHandleSessioning =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessioning
typealias WireGuardKitDeepBackedHandleSessionCreating =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionCreating
typealias WireGuardKitDeepBackedHandleSessionFactorying =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionFactorying
typealias WireGuardKitDeepBackedHandleSession =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSession
typealias UnavailableWireGuardKitDeepBackedHandleSessionCreator =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionCreator
typealias WireGuardKitDeepBackedHandleSessionCreator =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionCreator
typealias UnavailableWireGuardKitDeepBackedHandleSessionFactory =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionFactory
typealias WireGuardKitDeepBackedHandleSessionFactory =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionFactory

typealias WireGuardKitDeepLeafHandleConfiguration =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionHandleConfiguration
typealias WireGuardKitDeepLeafHandleConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionHandleConfigurationMapper
typealias WireGuardKitDeepLeafHandleTerminalConfigurationMapper =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionHandleTerminalConfigurationMapper
typealias WireGuardKitDeepLeafHandleControlling =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionHandleControlling
typealias WireGuardKitDeepLeafHandleCreating =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionHandleCreating
typealias WireGuardKitDeepLeafHandleFactorying =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionHandleFactorying
typealias WireGuardKitDeepLeafHandle =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionHandle
typealias UnavailableWireGuardKitDeepLeafHandleCreator =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionHandleCreator
typealias WireGuardKitDeepLeafHandleCreator =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionHandleCreator
typealias UnavailableWireGuardKitDeepLeafHandleFactory =
  UnavailableWireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionHandleFactory
typealias WireGuardKitDeepLeafHandleFactory =
  WireGuardKitAdapterBackedSessionAdapterHandleNativeHandleSessionHandleRuntimeHandleSessionBackedSessionHandleSessionHandleFactory
