[package]
name = "app-core-cli"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
control-mqtt-client = { path = "../control-mqtt-client" }
controller-client = { path = "../controller-client" }
ffi-bridge = { path = "../ffi-bridge" }
p2p = { path = "../p2p" }
relay-client = { path = "../relay-client" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slan-app-core = { path = "../app-core" }
tunnel = { path = "../tunnel" }
