export const OPS_API = {
  authLogin: '/api/ops/auth/login',
  authPassword: '/api/ops/auth/password',
  operators: '/api/ops/operators',
  operator: (operatorId: string) => `/api/ops/operators/${encodeURIComponent(operatorId)}`,
  operatorPassword: (operatorId: string) => `/api/ops/operators/${encodeURIComponent(operatorId)}/password`,
  relayNodes: '/api/ops/relay-nodes',
  relayNode: (nodeId: string) => `/api/ops/relay-nodes/${encodeURIComponent(nodeId)}`,
  relayNodeStatus: (nodeId: string) => `/api/ops/relay-nodes/${encodeURIComponent(nodeId)}/status`,
  punchNodes: '/api/ops/punch-nodes',
  punchNode: (nodeId: string) => `/api/ops/punch-nodes/${encodeURIComponent(nodeId)}`,
  punchNodeStatus: (nodeId: string) => `/api/ops/punch-nodes/${encodeURIComponent(nodeId)}/status`,
  users: '/api/ops/users',
  user: (userId: string) => `/api/ops/users/${encodeURIComponent(userId)}`,
  userPassword: (userId: string) => `/api/ops/users/${encodeURIComponent(userId)}/password`,
  devices: '/api/ops/devices',
  device: (deviceId: string) => `/api/ops/devices/${encodeURIComponent(deviceId)}`,
  deviceGroups: '/api/ops/device-groups',
  deviceGroup: (groupId: string) => `/api/ops/device-groups/${encodeURIComponent(groupId)}`,
  deviceGroupMembers: (groupId: string, ownerId: string) => `/api/ops/device-groups/${encodeURIComponent(groupId)}/members?ownerId=${encodeURIComponent(ownerId)}`,
  deviceGroupsForDevice: (deviceId: string) => `/api/ops/devices/${encodeURIComponent(deviceId)}/groups`,
  networks: '/api/ops/networks',
  network: (networkId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}`,
  networkDevices: (networkId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/devices`,
  networkDevice: (networkId: string, deviceId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/devices/${encodeURIComponent(deviceId)}`,
  networkDeviceGroups: (networkId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/device-groups`,
  networkDeviceGroup: (networkId: string, groupId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/device-groups/${encodeURIComponent(groupId)}`,
  securityGroups: (networkId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/security-groups`,
  securityGroup: (groupId: string) => `/api/ops/security-groups/${encodeURIComponent(groupId)}`,
  securityRules: (groupId: string) => `/api/ops/security-groups/${encodeURIComponent(groupId)}/rules`,
  securityRule: (ruleId: string) => `/api/ops/security-rules/${encodeURIComponent(ruleId)}`,
  dnsZones: (networkId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/dns/zones`,
  dnsZone: (zoneId: string) => `/api/ops/dns/zones/${encodeURIComponent(zoneId)}`,
  dnsRecords: (networkId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/dns/records`,
  dnsRecord: (recordId: string) => `/api/ops/dns/records/${encodeURIComponent(recordId)}`,
} as const;
