export const OPS_API = {
  authLogin: '/api/ops/auth/login',
  authPassword: '/api/ops/auth/password',
  operators: '/api/ops/operators',
  operator: (operatorId: string) => `/api/ops/operators/${encodeURIComponent(operatorId)}`,
  operatorPassword: (operatorId: string) => `/api/ops/operators/${encodeURIComponent(operatorId)}/password`,
  relayNodes: '/api/ops/relay-nodes',
  relayNode: (nodeId: string) => `/api/ops/relay-nodes/${encodeURIComponent(nodeId)}`,
  relayNodeStatus: (nodeId: string) => `/api/ops/relay-nodes/${encodeURIComponent(nodeId)}/status`,
  punchNodes: '/api/ops/punch-nodes',
  punchNode: (nodeId: string) => `/api/ops/punch-nodes/${encodeURIComponent(nodeId)}`,
  punchNodeStatus: (nodeId: string) => `/api/ops/punch-nodes/${encodeURIComponent(nodeId)}/status`,
  customers: '/api/ops/customers',
  customer: (customerId: string) => `/api/ops/customers/${encodeURIComponent(customerId)}`,
  customerAssignPlan: (customerId: string) => `/api/ops/customers/${encodeURIComponent(customerId)}/assign-plan`,
  devices: '/api/ops/devices',
  device: (deviceId: string) => `/api/ops/devices/${encodeURIComponent(deviceId)}`,
  clientDownloads: '/api/ops/client-downloads',
  clientDownload: (downloadId: string) => `/api/ops/client-downloads/${encodeURIComponent(downloadId)}`,
  plans: '/api/ops/plans',
  plan: (planCode: string) => `/api/ops/plans/${encodeURIComponent(planCode)}`,
  products: '/api/ops/products',
  product: (productId: string) => `/api/ops/products/${encodeURIComponent(productId)}`,
  orders: '/api/ops/orders',
  order: (orderId: string) => `/api/ops/orders/${encodeURIComponent(orderId)}`,
  renewals: '/api/ops/renewals',
  renewal: (renewalId: string) => `/api/ops/renewals/${encodeURIComponent(renewalId)}`,
} as const;
