export const OPS_API = {
  authLogin: '/api/ops/auth/login',
  authLogout: '/api/ops/auth/logout',
  authPassword: '/api/ops/auth/password',
  auditEvents: '/api/ops/audit-events',
  operators: '/api/ops/operators',
  operator: (operatorId: string) => `/api/ops/operators/${encodeURIComponent(operatorId)}`,
  operatorPassword: (operatorId: string) => `/api/ops/operators/${encodeURIComponent(operatorId)}/password`,
  serverNodes: '/api/ops/server-nodes',
  serverNode: (nodeId: string) => `/api/ops/server-nodes/${encodeURIComponent(nodeId)}`,
  serverNodeHostKey: (nodeId: string) => `/api/ops/server-nodes/${encodeURIComponent(nodeId)}/ssh-host-key`,
  serverNodeDeploy: (nodeId: string) => `/api/ops/server-nodes/${encodeURIComponent(nodeId)}/deploy`,
  customers: '/api/ops/customers',
  customer: (customerId: string) => `/api/ops/customers/${encodeURIComponent(customerId)}`,
  devices: '/api/ops/devices',
  device: (deviceId: string) => `/api/ops/devices/${encodeURIComponent(deviceId)}`,
  deviceCredentials: '/api/ops/device-credentials',
  networks: '/api/ops/networks',
  network: (networkId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}`,
  networkDeviceGroups: (networkId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/device-groups`,
  networkDeviceGroup: (networkId: string, groupId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/device-groups/${encodeURIComponent(groupId)}`,
  networkDNSZones: (networkId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/dns/zones`,
  networkPolicy: (networkId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/policy`,
  dnsZone: (zoneId: string) => `/api/ops/dns/zones/${encodeURIComponent(zoneId)}`,
  networkDNSRecords: (networkId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/dns/records`,
  dnsRecord: (recordId: string) => `/api/ops/dns/records/${encodeURIComponent(recordId)}`,
  networkSecurityGroups: (networkId: string) => `/api/ops/networks/${encodeURIComponent(networkId)}/security-groups`,
  securityGroup: (securityGroupId: string) => `/api/ops/security-groups/${encodeURIComponent(securityGroupId)}`,
  securityGroupRules: (securityGroupId: string) => `/api/ops/security-groups/${encodeURIComponent(securityGroupId)}/rules`,
  securityRule: (ruleId: string) => `/api/ops/security-rules/${encodeURIComponent(ruleId)}`,
  deviceGroups: '/api/ops/device-groups',
  deviceGroup: (groupId: string) => `/api/ops/device-groups/${encodeURIComponent(groupId)}`,
  deviceGroupDevices: (groupId: string) => `/api/ops/device-groups/${encodeURIComponent(groupId)}/devices`,
  deviceGroupDevice: (groupId: string, deviceId: string) => `/api/ops/device-groups/${encodeURIComponent(groupId)}/devices/${encodeURIComponent(deviceId)}`,
} as const;
